### PR TITLE
Offset: fix wrong origin value

### LINKED ISSUE #330: Why `offset` is restored to return `{ left: 0, top: 0}` in 3.1.0?
jQuery 2.2.4 is already returning `undefined` for an empty collection. Why jquery-migrate 3.1.0 is restoring it to return `{ left: 0, top: 0 }`?

https://github.com/jquery/jquery-migrate/blob/3.1.0/src/offset.js

### PR DESCRIPTION
**Pull request by panlina**
Fixes #330 .

`offset` should return `undefined` instead of `{top:0,left:0}` for non DOM element.

### CODE REVIEW

**Comment by panlina** [comment]
When will this be merged?

**Comment by mgol** [comment]
I'd like @dmethvin to do a review as well but I'd like to get it in a Migrate 3.2.0 release that is likely to be available within a week or two.

File: src/offset.js [hunk 1]
```diff
@@ -4,17 +4,17 @@ var oldOffset = jQuery.fn.offset;
 jQuery.fn.offset = function() {
 	var docElem,
 		elem = this[ 0 ],
-		origin = { top: 0, left: 0 };
+		bogus = { top: 0, left: 0 };
 
 	if ( !elem || !elem.nodeType ) {
 		migrateWarn( "jQuery.fn.offset() requires a valid DOM element" );
-		return origin;
```
Comment (dmethvin) [inline src/offset.js:11]: We only want to return `undefined` for the `!elem` case. Some code including older older versions of jQuery UI would pass `window` and expect the top/left of 0. https://github.com/jquery/jquery/issues/3249

Comment (panlina) [reply src/offset.js:11]: Does it expect `{left:0,top:0}` for `window`? Why both `1.12.4` and `2.2.4` return `undefined` as I tested?

Comment (dmethvin) [reply src/offset.js:11]: It sure does, thanks for catching that! I don't have time to look at it right now but I must have been thinking of some other edge case with `.offset()`? Looks like that ticket is specifically about calling a method on `window`, not returning the bogus value.

Comment (mgol) [reply src/offset.js:11]: @dmethvin Since the issue was about a breaking change in jQuery 3.0.0, it seems we shouldn't care about it here as Migrate 3.x is meant to aid with upgrading to the future jQuery 4.0. Am I missing anything?
